### ISSUE TITLE
Averaging measured slurry temperature

### ISSUE THREAD

**Issue by sashahafner** [Chih-yuHung/STM-and-1D-model#2]
I think we should only use an upper and lower location for averaging.
Otherwise when slurry level is low we have multiple sensors at the bottom and therefore it gets more weight in the calculation of the average than other depths.
Should we include surface measurement too? 
I don't think so because the temperature gradient is so high at the surface that surface is not representative of bulk.
We can check though.

**Comment by Chih-yuHung** [comment]
Just a note here for our discussion later. 
![image](https://user-images.githubusercontent.com/93739872/221630526-d1267c4d-a7da-49e9-a5db-c65af83aa8ab.png)
This method can be used to obtain the weighted average temperature. But based on my experience, the difference is not significant.

**Comment by sashahafner** [comment]
Can you remind me how you calculated `temp.avg` for Ottawa in this file @Chih-yuHung ?

https://github.com/Chih-yuHung/STM-and-1D-model/blob/main/temp-meas/data-meas/Ottawa_H_storage_temp.csv

**Comment by sashahafner** [comment]
Hmm, the values look strange.
`temp.avg` peaks in April and is low during the summer.
Here in August it is below all the temperature sensor measurements:

![image](https://github.com/Chih-yuHung/STM-and-1D-model/assets/35272876/30f671b4-7606-41c9-a7fd-b08bcdc489e1)

**Comment by Chih-yuHung** [comment]
Unfortunately, I cannot remember how I calculate the average temperature in https://github.com/Chih-yuHung/STM-and-1D-model/blob/main/temp-meas/data-meas/Ottawa_H_storage_temp.csv

I checked the data and you're right that the average temperatures look weird. I suggest using the average temperature of `temp.up`, `temp.m`, and `temp.b` to do the comparison.

**Comment by sashahafner** [comment]
OK thanks.
I just reverted 162632e2323c90ac3c472488f9794421d91bdbec

**Comment by sashahafner** [comment]
We should probably remove that `temp.avg` column to avoid future confusion
